# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/AsyncTimer.xcworkspace -scheme AsyncTimer-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - WORKSPACE=AsyncTimer.xcworkspace
  - IOS="iOS"
  - MACOS="macOS"
  - TVOS="tvOS"
  - WATCHOS="watchOS"

  matrix:
    - DESTINATION="OS=9.0,name=iPad 2"                        PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES"  
    - DESTINATION="OS=9.1,name=iPad Air"                      PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=9.2,name=iPad Air 2"                    PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.0,name=iPad Pro (9.7-inch)"          PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.1,name=iPad Pro (12.9-inch)"         PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 

    - DESTINATION="OS=9.0,name=iPhone 4s"                     PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=9.1,name=iPhone 5"                      PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=9.2,name=iPhone 5s"                     PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=9.3,name=iPhone 6"                      PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.0,name=iPhone 6 Plus"                PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.1,name=iPhone 6s"                    PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.2,name=iPhone 6s Plus"               PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.1,name=iPhone 7"                     PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"                PLATFORM="$IOS"       RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 

    - DESTINATION="OS=2.0,name=Apple Watch - 38mm"            PLATFORM="$WATCHOS"   RUN_TESTS="NO"    BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO" 
    - DESTINATION="OS=2.2,name=Apple Watch - 42mm"            PLATFORM="$WATCHOS"   RUN_TESTS="NO"    BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO" 
    - DESTINATION="OS=3.1,name=Apple Watch - 42mm"            PLATFORM="$WATCHOS"   RUN_TESTS="NO"    BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO" 
    - DESTINATION="OS=3.1,name=Apple Watch Series 2 - 38mm"   PLATFORM="$WATCHOS"   RUN_TESTS="NO"    BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO" 
    - DESTINATION="OS=3.2,name=Apple Watch Series 2 - 42mm"   PLATFORM="$WATCHOS"   RUN_TESTS="NO"    BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO" 

    - DESTINATION="OS=10.3.1,name=iPhone 6s"                  PLATFORM="$WATCHOS"   RUN_TESTS="NO"    BUILD_FRAMEWORK="NO"  BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.3.1,name=iPhone 6s Plus"             PLATFORM="$WATCHOS"   RUN_TESTS="NO"    BUILD_FRAMEWORK="NO"  BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.3.1,name=iPhone 7"                   PLATFORM="$WATCHOS"   RUN_TESTS="NO"    BUILD_FRAMEWORK="NO"  BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"              PLATFORM="$WATCHOS"   RUN_TESTS="NO"    BUILD_FRAMEWORK="NO"  BUILD_EXAMPLE="YES" 

    - DESTINATION="OS=9.0,name=Apple TV 1080p"                PLATFORM="$TVOS"      RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=9.1,name=Apple TV 1080p"                PLATFORM="$TVOS"      RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=9.2,name=Apple TV 1080p"                PLATFORM="$TVOS"      RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.0,name=Apple TV 1080p"               PLATFORM="$TVOS"      RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.1,name=Apple TV 1080p"               PLATFORM="$TVOS"      RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 
    - DESTINATION="OS=10.2,name=Apple TV 1080p"               PLATFORM="$TVOS"      RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 

    - DESTINATION="arch=x86_64"                               PLATFORM="$MACOS"     RUN_TESTS="YES"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="YES" 

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - FRAMEWORK_SCHEME="AsyncTimer $PLATFORM";

  # Build Framework
  # - if [ $BUILD_FRAMEWORK == "YES" ]; then
  #     xcodebuild -workspace "$WORKSPACE" -scheme "$FRAMEWORK_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
  #     xcodebuild -workspace "$WORKSPACE" -scheme "$FRAMEWORK_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build| xcpretty;
  #   fi
  
  # # Build Example
  # - if [ $BUILD_EXAMPLE == "YES" ]; then
  #     xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
  #     xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build| xcpretty;
  #   fi
  
  # # Run Tests
  # - if [ $RUN_TESTS == "YES" ]; then
  #     xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
  #     xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
  #   fi
  
after_script:
  - pod try AsyncTimer;
